swagger: '2.0'
info:
  title: IdeaMarket API
  description: IdeaMarket API Definition
  version: '0.2.0'
# the domain of the service
host: localhost:1337
# array of all schemes that your API supports
schemes:
  - http
# will be prefixed to all paths
basePath: /api/v1
produces:
  - application/json
paths:
  /auth:
    post:
      description: Used to create new authentication credentials. 
      parameters:
        - name: authentication
          in: body
          description: The authentication JSON to be used for authentication
          schema:
            $ref: '#/definitions/Authentication'
          required: true
      tags:
        - Authentication
      responses:
        200:
          description: Creates new authentication credentials
  /auth/login:
    post:
      parameters:
        - name: idea
          in: body
          description: The authentication JSON to be used for authentication
          schema:
            $ref: '#/definitions/Authentication'
          required: true
      tags:
        - Authentication
      responses:
        200:
          description: User was successfully logged-in into the system
  /auth/changepassword:
    put:
      parameters:
        - name: idea
          in: body
          description: The idea JSON you want to post
          schema:
            $ref: '#/definitions/Authentication'
          required: true
      tags:
        - Authentication
      responses:
        200:
          description: User password was successfully updated.
  /ideas:
    get:
      summary: Idea Information
      description: |
        The endpoint returns information about a idea.
      parameters:
        - name: q
          in: query
          description: The search string for the idea. This will be match againts the idea title, content, and tags
          required: false
          type: string
      tags:
        - Ideas
      responses:
        200:
          description: An array of ideas
          schema:
            type: array
            items:
              $ref: '#/definitions/Idea'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
    post:
      parameters:
        - name: idea
          in: body
          description: The idea JSON you want to post
          schema:
            $ref: '#/definitions/Idea'
          required: true
      tags:
        - Ideas
      responses:
        200:
          description: Make a new idea
  /ideas/{guid}:
    get:
      parameters:
        - name: guid
          in: path
          type: string
          description: ID of the idea
          required: true
      tags:
        - Ideas
      responses:
        200:
          description: Sends the Idea with GUID
    put:
      parameters:
        - name: guid
          in: path
          type: string
          description: ID of the idea
          required: true
        - name: body
          in: body
          description: the description
          required: false
          schema:
            $ref: '#/definitions/Idea'
      tags:
        - Ideas
      responses:
        200:
          description: Sends the User with GUID        
  /ideas/{guid}/comments:
    post:
      description: adds a comment to an idea
      parameters:
        - name: guid
          in: path
          type: string
          description: ID of the idea to which the comment will be added
          required: true
        - name: comment
          in: body
          description: Adds a comment to an Idea
          schema:
            $ref: '#/definitions/Comment'
          required: true
      responses:
        200:
          description: A new comment was added to the idea
  /ideas/{guid}/stat:
    get:
      description: request for the statistics
      parameters:
        - name: guid
          in: path
          type: string
          description: ID of the idea to which the comment will be added
          required: true
      responses:
        200:
          description: An array of ideas
          schema:
           $ref: '#/definitions/IdeaStat'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /users:
    get:
      summary: User Information
      description: |
        The endpoint returns information about a user.
      parameters:
        - name: username
          in: query
          description: The username the user.
          required: false
          type: string
      tags:
        - Users
      responses:
        200:
          description: An array of products
          schema:
            type: array
            items:
              $ref: '#/definitions/User'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
    post:
      parameters:
        - name: user
          in: body
          description: The user JSON you want to post
          schema:
            $ref: '#/definitions/User'
          required: true
      tags:
        - Users
      responses:
        200:
          description: Make a new user
  /users/{guid}:
    get:
      parameters:
        - name: guid
          in: path
          type: string
          description: ID of the user
          required: true
      tags:
        - Users
      responses:
        200:
          description: Sends the User with GUID
    put:
      parameters:
        - name: guid
          in: path
          type: string
          description: ID of the user
          required: true
        - name: body
          in: body
          description: the description
          required: false
          schema:
            $ref: '#/definitions/User'
      tags:
        - Users
      responses:
        200:
          description: Sends the User with GUID
  /users/{guid}/stat:
    get:
      parameters:
        - name: guid
          in: path
          type: string
          description: ID of the user
          required: true
      tags:
        - Users
      responses:
        200:
          description: Sends the User stat
          schema:
            $ref: '#/definitions/UserStat'
definitions:
 Authentication:
  type: object
  description: Information to be used for user authentication.
  properties:
    id:
      type: integer
      format: int64
      description: primary key. auto-generated if not supplied
    username:
      type: string
    password:
      type: string
      format: password
  required: ['username', 'password']
 Brand:
  type: object
  description: Existing brands i.e. Uber
  properties:
    id:
      type: integer
      format: int64
      description: primary key. not required. value is autogenerated
    name:
      type: string
      description: the popular name for the brand i.e. Uber
    official_name:
      type: string
      description: the formal name or could be the company name i.e. Uber Technologies Inc.
    url:
      type: string
      description: url for the brand
  required: ['id', 'name']
 Comment:
  type: object
  description: Idea comment. Introduced to cultivate interaction among members, to provide feedback on an Idea and make it more stronger. Allow only 2 levels of comment.
  properties:
    id:
      type: integer
      format: int64
      description: primary key. value is auto-generated
    author:
       $ref: '#/definitions/User'
    parent:
       $ref: '#/definitions/Comment'
    detail:
      type: string
      description: the comment content
    lastUpdateAt:
      type: string
      format: dateTime
      description: auto-generated by the system.
  required: ['id', 'author']
 Error:
  type: object
  properties:
    code:
      type: integer
      format: int32
    message:
      type: string
    fields:
      type: string
  required: ['code', 'message']
 Idea:
  type: object
  description: Idea posted on IdeaMarket
  properties:
    access:
      type: string
      enum: ['public', 'private', 'protected']
      description: the access type for the idea |
                  defaults to public if not supplied |
                  Public - accessible to everyone, even users not logged-in to the application. No credits required to view. Search engine can crawl on the idea

                  Protected - Only logged-in users will be able to access it. Credit is required to view and set by the Ideator.  Can also be used when posting jobs. Search engine cannot crawl on the content of the idea.
                  
                  Private - Only logged-in users will be able to access it. Ideator will need to send invitation to other users to gain access to the idea. Ideators are charged for every private idea they create. This is for an Idea internally develop
    businessModel:
      type: string
      description: The business model for the Idea. Protected Ideas is advised to have this for viewers to like it after spending credits.
    comments:
      type: array
      items: 
        $ref: '#/definitions/Comment'
    detail:
      type: string
      description: idea full details
    guid:
      type: string
      description: Auto-generated if not supplied. Unique identifier for the Idea.
    ideator:
      type: string
      description: User GUID.
    status:
      type: string
      enum: ['draft', 'published']
      default: 'draft'
      description: Defaults to draft. | Only published ideas are searchable.
    similarApplications:
      type: array
      items:
        $ref: '#/definitions/Brand'
    stat:
      type: integer
      format: int64
      description: IdeaStat GUID. During creation of Idea if not present, the object will be auto-generated.
    tags:
     type: array
     description: can be used to filter and search ideas
     items: 
      type: string
    title:
      type: string
      description: A short description for the Idea. The text to show on a list
  required: ['detail', 'ideator', 'title']
 IdeaStat:
  type: object
  description: Idea statistics. Useful statistics to aid users when selecting ideas to view. Users are expected to view ideas with high views and likes.
  properties:
    id:
      type: integer
      format: int64
      description: primary key. value is autogenerated
    userViews:
      type: array
      items:
        $ref: '#/definitions/User'
    views:
      type: integer
      format: int32
      description: Every request in an Idea is counted as view even failed one. However, large number of views doesn't guarantee a strong idea since this can be exploited. The count is the total of protected and public views. if not for the public views we woudn't be needing this and will just use userViews size.
    likes:
      type: array
      items:
        $ref: '#/definitions/User'
    points:
      type: integer
      format: int32
      description: useful when calculating for a User's reputation. Points will come from number of views, number of likes, and number of comments. this only increases.
 User:
  type: object
  properties:
    id:
      type: string
      description: GUID. Auto-generated if not supplied
    name:
      type: string
      description: the name of the user that will be displayed in the application
    bio:
      type: string
      description: a short description for the user
    website:
      type: string
      description: the user's website
    auth:
      type: integer
      format: int64
      description: Authentication ID
    stat:
      type: integer
      format: int64
      description: UserStat ID
  required: ['name', 'auth']
 UserStat:
  type: object
  description: Useful information before viewing a new idea. If the views and likes are small, viewers can check the ideators statistics before deciding to past or continue viewing the idea.
    stat is updated every time an update on idea is performed.
  properties:
    id:
      type: integer
      format: int64
      description: primary key. value is autogenerated
    reputation:
      type: integer
      format: int32
      description: Reputation points will come from ideas posted and comments given. Idea points will come from likes and views.
    ideas:
      type: integer
      format: int32
      description: The total number of the ideas the Ideator has published.