swagger: '2.0'
info:
  title: IdeaMarket API
  description: IdeaMarket API Definition
  version: "0.1.0"
# the domain of the service
host: localhost:1337
# array of all schemes that your API supports
schemes:
  - http
# will be prefixed to all paths
basePath: /api/v1
produces:
  - application/json
paths:
  /ideas:
    get:
      summary: Idea Information
      description: |
        The endpoint returns information about a idea.
      parameters:
        - name: search
          in: query
          description: The search string for the idea. This will be match againts the idea title, content, and tags
          required: false
          type: string
      tags:
        - Ideas
      responses:
        200:
          description: An array of ideas
          schema:
            type: array
            items:
              $ref: '#/definitions/Idea'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
    post:
      parameters:
        - name: idea
          in: body
          description: The idea JSON you want to post
          schema:
            $ref: '#/definitions/Idea'
          required: true
      tags:
        - Ideas
      responses:
        200:
          description: Make a new idea
  /ideas/{guid}:
    get:
      parameters:
        - name: guid
          in: path
          type: string
          description: ID of the idea
          required: true
      tags:
        - Ideas
      responses:
        200:
          description: Sends the Idea with GUID
    put:
      parameters:
        - name: guid
          in: path
          type: string
          description: ID of the idea
          required: true
        - name: body
          in: body
          description: the description
          required: false
          schema:
            $ref: '#/definitions/Idea'
      tags:
        - Ideas
      responses:
        200:
          description: Sends the User with GUID        
  /users:
    get:
      summary: User Information
      description: |
        The endpoint returns information about a user.
      parameters:
        - name: username
          in: query
          description: The username the user.
          required: false
          type: string
      tags:
        - Users
      responses:
        200:
          description: An array of products
          schema:
            type: array
            items:
              $ref: '#/definitions/User'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
    post:
      parameters:
        - name: user
          in: body
          description: The user JSON you want to post
          schema:
            $ref: '#/definitions/User'
          required: true
      tags:
        - Users
      responses:
        200:
          description: Make a new user
  /users/{guid}:
    get:
      parameters:
        - name: guid
          in: path
          type: string
          description: ID of the user
          required: true
      tags:
        - Users
      responses:
        200:
          description: Sends the User with GUID
    put:
      parameters:
        - name: guid
          in: path
          type: string
          description: ID of the user
          required: true
        - name: body
          in: body
          description: the description
          required: false
          schema:
            $ref: '#/definitions/User'
      tags:
        - Users
      responses:
        200:
          description: Sends the User with GUID
definitions:
 Authentication:
  type: object
  description: Information to be used for user authentication.
  properties:
    id:
      type: integer
      format: int64
      description: primary key
    username:
      type: string
    password:
      type: string
      format: password
 Brand:
  type: object
  description: Existing brands i.e. Uber
  properties:
    id:
      type: integer
      format: int64
      description: primary key. not required. value is autogenerated
    name:
      type: string
      description: the popular name for the brand i.e. Uber
    officialName:
      type: string
      description: the formal name or could be the company name i.e. Uber Technologies Inc.
    url:
      type: string
      description: url for the brand
 Comment:
  type: object
  description: Idea comment. Introduced to cultivate interaction among members, to provide feedback on an Idea and make it more stronger. Allow only 2 levels of comment.
  properties:
    id:
      type: integer
      format: int64
      description: primary key. value is autogenerated
    author:
      type: string
      description: User GUID
    parent:
      type: integer
      format: int64
      description: Comment ID. If present the comment is already a second level comment. Additional comment will be added on the same thread.
    detail:
      type: string
      description: the comment content
    lastUpdateAt:
      type: string
      format: dateTime
      description: the idea created date
 Error:
  type: object
  properties:
    code:
      type: integer
      format: int32
    message:
      type: string
    fields:
      type: string
 Idea:
  type: object
  description: Idea posted on IdeaMarket
  properties:
    access:
      type: string
      enum: ['public', 'private', 'protected']
      description: the access type for the idea |
                  Public - accessible to everyone, even users not logged-in to the application. No credits required to view. Search engine can crawl on the idea

                  Protected - Only logged-in users will be able to access it. Credit is required to view and set by the Ideator.  Can also be used when posting jobs. Search engine cannot crawl on the content of the idea.
                  
                  Private - Only logged-in users will be able to access it. Ideator will need to send invitation to other users to gain access to the idea. Ideators are charged for every private idea they create. This is for an Idea internally develop
    businessModel:
      type: string
      description: The business model for the Idea. Protected Ideas is advised to have this for viewers to like it after spending credits.
    comments:
      type: array
      items: 
        $ref: '#/definitions/Comment'
    dateCreated:
      type: string
      format: dateTime
      description: the idea created date
    detail:
      type: string
      description: idea full details
    guid:
      type: string
      description: Unique identifier for the Idea
    ideator:
      $ref: '#/definitions/User'
    status:
      type: string
      enum: ['draft', 'published']
      description: only published ideas are searchable. draft is the default status when a task is created
    similarApplications:
      type: array
      items:
        $ref: '#/definitions/Brand'
    stat:
      $ref: '#/definitions/IdeaStat'
    tags:
     type: array
     description: can be used to filter and search ideas
     items: 
      type: string
    title:
      type: string
      description: A short description for the Idea. The text to show on a list
 IdeaStat:
  type: object
  description: Idea statistics. Useful statistics to aid users when selecting ideas to view. Users are expected to view ideas with high views and likes.
  properties:
    id:
      type: integer
      format: int64
      description: primary key. value is autogenerated
    userViews:
      type: array
      items:
        $ref: '#/definitions/User'
    views:
      type: integer
      format: int32
      description: Every request in an Idea is counted as view even failed one. However, large number of views doesn't guarantee a strong idea since this can be exploited. The count is the total of protected and public views. if not for the public views we woudn't be needing this and will just use userViews size.
    likes:
      type: array
      items:
        $ref: '#/definitions/User'
    points:
      type: integer
      format: int32
      description: useful when calculating for a User's reputation. Points will come from number of views, number of likes, and number of comments. this only increases.
 User:
  type: object
  properties:
    guid:
      type: string
      description: Unique identifier for the User
    name:
      type: string
      description: the name of the user that will be displayed in the application
    dateCreated:
      type: string
      format: dateTime
      description: account creation date. helpful when 
    auth:
      $ref: '#/definitions/Authentication'
    stat:
      $ref: '#/definitions/UserStat'
 UserStat:
  type: object
  description: Useful information before viewing a new idea. If the views and likes are small, viewers can check the ideators statistics before deciding to past or continue viewing the idea.
    stat is updated every time an update on idea is performed.
  properties:
    id:
      type: integer
      format: int64
      description: primary key. value is autogenerated
    reputation:
      type: integer
      format: int32
      description: Reputation points will come from ideas posted and comments given. Idea points will come from likes and views.
    ideas:
      type: integer
      format: int32
      description: The total number of the ideas the Ideator has published.